/*
 * Copyright 2012-2016 eiennohito (Tolmachev Arseny)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package mecab;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Path structure<br>
 * <i>native declaration : line 54</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mecab")
public class mecab_path_t extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : mecab_node_t* */
	@Field(0)
	public Pointer<mecab_node_t > rnode() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : mecab_node_t* */
	@Field(0)
	public mecab_path_t rnode(Pointer<mecab_node_t > rnode) {
		this.io.setPointerField(this, 0, rnode);
		return this;
	}
	/** C type : mecab_path_t* */
	@Field(1)
	public Pointer<mecab_path_t > rnext() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : mecab_path_t* */
	@Field(1)
	public mecab_path_t rnext(Pointer<mecab_path_t > rnext) {
		this.io.setPointerField(this, 1, rnext);
		return this;
	}
	/** C type : mecab_node_t* */
	@Field(2)
	public Pointer<mecab_node_t > lnode() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : mecab_node_t* */
	@Field(2)
	public mecab_path_t lnode(Pointer<mecab_node_t > lnode) {
		this.io.setPointerField(this, 2, lnode);
		return this;
	}
	/** C type : mecab_path_t* */
	@Field(3)
	public Pointer<mecab_path_t > lnext() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : mecab_path_t* */
	@Field(3)
	public mecab_path_t lnext(Pointer<mecab_path_t > lnext) {
		this.io.setPointerField(this, 3, lnext);
		return this;
	}
	@Field(4)
	public int cost() {
		return this.io.getIntField(this, 4);
	}
	@Field(4)
	public mecab_path_t cost(int cost) {
		this.io.setIntField(this, 4, cost);
		return this;
	}
	@Field(5)
	public float prob() {
		return this.io.getFloatField(this, 5);
	}
	@Field(5)
	public mecab_path_t prob(float prob) {
		this.io.setFloatField(this, 5, prob);
		return this;
	}
	public mecab_path_t() {
		super();
	}
	public mecab_path_t(Pointer pointer) {
		super(pointer);
	}
}
