package mecab;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Node structure<br>
 * <i>native declaration : line 99</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mecab") 
public class mecab_node_t extends StructObject {
	public mecab_node_t() {
		super();
	}
	/**
	 * pointer to the previous node.<br>
	 * C type : mecab_node_t*
	 */
	@Field(0) 
	public Pointer<mecab_node_t > prev() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * pointer to the previous node.<br>
	 * C type : mecab_node_t*
	 */
	@Field(0) 
	public mecab_node_t prev(Pointer<mecab_node_t > prev) {
		this.io.setPointerField(this, 0, prev);
		return this;
	}
	/**
	 * pointer to the next node.<br>
	 * C type : mecab_node_t*
	 */
	@Field(1) 
	public Pointer<mecab_node_t > next() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * pointer to the next node.<br>
	 * C type : mecab_node_t*
	 */
	@Field(1) 
	public mecab_node_t next(Pointer<mecab_node_t > next) {
		this.io.setPointerField(this, 1, next);
		return this;
	}
	/**
	 * pointer to the node which ends at the same position.<br>
	 * C type : mecab_node_t*
	 */
	@Field(2) 
	public Pointer<mecab_node_t > enext() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * pointer to the node which ends at the same position.<br>
	 * C type : mecab_node_t*
	 */
	@Field(2) 
	public mecab_node_t enext(Pointer<mecab_node_t > enext) {
		this.io.setPointerField(this, 2, enext);
		return this;
	}
	/**
	 * pointer to the node which starts at the same position.<br>
	 * C type : mecab_node_t*
	 */
	@Field(3) 
	public Pointer<mecab_node_t > bnext() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * pointer to the node which starts at the same position.<br>
	 * C type : mecab_node_t*
	 */
	@Field(3) 
	public mecab_node_t bnext(Pointer<mecab_node_t > bnext) {
		this.io.setPointerField(this, 3, bnext);
		return this;
	}
	/**
	 * pointer to the right path.<br>
	 * this value is NULL if MECAB_ONE_BEST mode.<br>
	 * C type : mecab_path_t*
	 */
	@Field(4) 
	public Pointer<mecab_path_t > rpath() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * pointer to the right path.<br>
	 * this value is NULL if MECAB_ONE_BEST mode.<br>
	 * C type : mecab_path_t*
	 */
	@Field(4) 
	public mecab_node_t rpath(Pointer<mecab_path_t > rpath) {
		this.io.setPointerField(this, 4, rpath);
		return this;
	}
	/**
	 * pointer to the right path.<br>
	 * this value is NULL if MECAB_ONE_BEST mode.<br>
	 * C type : mecab_path_t*
	 */
	@Field(5) 
	public Pointer<mecab_path_t > lpath() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * pointer to the right path.<br>
	 * this value is NULL if MECAB_ONE_BEST mode.<br>
	 * C type : mecab_path_t*
	 */
	@Field(5) 
	public mecab_node_t lpath(Pointer<mecab_path_t > lpath) {
		this.io.setPointerField(this, 5, lpath);
		return this;
	}
	/**
	 * surface string.<br>
	 * this value is not 0 terminated.<br>
	 * You can get the length with length/rlength members.<br>
	 * C type : const char*
	 */
	@Field(6) 
	public Pointer<Byte > surface() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * surface string.<br>
	 * this value is not 0 terminated.<br>
	 * You can get the length with length/rlength members.<br>
	 * C type : const char*
	 */
	@Field(6) 
	public mecab_node_t surface(Pointer<Byte > surface) {
		this.io.setPointerField(this, 6, surface);
		return this;
	}
	/**
	 * feature string<br>
	 * C type : const char*
	 */
	@Field(7) 
	public Pointer<Byte > feature() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * feature string<br>
	 * C type : const char*
	 */
	@Field(7) 
	public mecab_node_t feature(Pointer<Byte > feature) {
		this.io.setPointerField(this, 7, feature);
		return this;
	}
	/// unique node id
	@Field(8) 
	public int id() {
		return this.io.getIntField(this, 8);
	}
	/// unique node id
	@Field(8) 
	public mecab_node_t id(int id) {
		this.io.setIntField(this, 8, id);
		return this;
	}
	/// length of the surface form/.
	@Field(9) 
	public short length() {
		return this.io.getShortField(this, 9);
	}
	/// length of the surface form/.
	@Field(9) 
	public mecab_node_t length(short length) {
		this.io.setShortField(this, 9, length);
		return this;
	}
	/// length of the surface form including white space before the morph.
	@Field(10) 
	public short rlength() {
		return this.io.getShortField(this, 10);
	}
	/// length of the surface form including white space before the morph.
	@Field(10) 
	public mecab_node_t rlength(short rlength) {
		this.io.setShortField(this, 10, rlength);
		return this;
	}
	/// right attribute id
	@Field(11) 
	public short rcAttr() {
		return this.io.getShortField(this, 11);
	}
	/// right attribute id
	@Field(11) 
	public mecab_node_t rcAttr(short rcAttr) {
		this.io.setShortField(this, 11, rcAttr);
		return this;
	}
	/// left attribute id
	@Field(12) 
	public short lcAttr() {
		return this.io.getShortField(this, 12);
	}
	/// left attribute id
	@Field(12) 
	public mecab_node_t lcAttr(short lcAttr) {
		this.io.setShortField(this, 12, lcAttr);
		return this;
	}
	/// unique part of speech id. This value is defined in "pos.def" file.
	@Field(13) 
	public short posid() {
		return this.io.getShortField(this, 13);
	}
	/// unique part of speech id. This value is defined in "pos.def" file.
	@Field(13) 
	public mecab_node_t posid(short posid) {
		this.io.setShortField(this, 13, posid);
		return this;
	}
	/// character type
	@Field(14) 
	public byte char_type() {
		return this.io.getByteField(this, 14);
	}
	/// character type
	@Field(14) 
	public mecab_node_t char_type(byte char_type) {
		this.io.setByteField(this, 14, char_type);
		return this;
	}
	/**
	 * statis of this model.<br>
	 * This value is MECAB_NOR_NODE, MECAB_UNK_NODE, MECAB_BOS_NODE, MECAB_EOS_NODE, or MECAB_EON_NODE.
	 */
	@Field(15) 
	public byte stat() {
		return this.io.getByteField(this, 15);
	}
	/**
	 * statis of this model.<br>
	 * This value is MECAB_NOR_NODE, MECAB_UNK_NODE, MECAB_BOS_NODE, MECAB_EOS_NODE, or MECAB_EON_NODE.
	 */
	@Field(15) 
	public mecab_node_t stat(byte stat) {
		this.io.setByteField(this, 15, stat);
		return this;
	}
	/// set 1 if this node is best node.
	@Field(16) 
	public byte isbest() {
		return this.io.getByteField(this, 16);
	}
	/// set 1 if this node is best node.
	@Field(16) 
	public mecab_node_t isbest(byte isbest) {
		this.io.setByteField(this, 16, isbest);
		return this;
	}
	/**
	 * forward accumulative log summation.<br>
	 * This value is only available when MECAB_MARGINAL_PROB is passed.
	 */
	@Field(17) 
	public float alpha() {
		return this.io.getFloatField(this, 17);
	}
	/**
	 * forward accumulative log summation.<br>
	 * This value is only available when MECAB_MARGINAL_PROB is passed.
	 */
	@Field(17) 
	public mecab_node_t alpha(float alpha) {
		this.io.setFloatField(this, 17, alpha);
		return this;
	}
	/**
	 * backward accumulative log summation.<br>
	 * This value is only available when MECAB_MARGINAL_PROB is passed.
	 */
	@Field(18) 
	public float beta() {
		return this.io.getFloatField(this, 18);
	}
	/**
	 * backward accumulative log summation.<br>
	 * This value is only available when MECAB_MARGINAL_PROB is passed.
	 */
	@Field(18) 
	public mecab_node_t beta(float beta) {
		this.io.setFloatField(this, 18, beta);
		return this;
	}
	/**
	 * marginal probability.<br>
	 * This value is only available when MECAB_MARGINAL_PROB is passed.
	 */
	@Field(19) 
	public float prob() {
		return this.io.getFloatField(this, 19);
	}
	/**
	 * marginal probability.<br>
	 * This value is only available when MECAB_MARGINAL_PROB is passed.
	 */
	@Field(19) 
	public mecab_node_t prob(float prob) {
		this.io.setFloatField(this, 19, prob);
		return this;
	}
	/// word cost.
	@Field(20) 
	public short wcost() {
		return this.io.getShortField(this, 20);
	}
	/// word cost.
	@Field(20) 
	public mecab_node_t wcost(short wcost) {
		this.io.setShortField(this, 20, wcost);
		return this;
	}
	/// best accumulative cost from bos node to this node.
	@CLong 
	@Field(21) 
	public long cost() {
		return this.io.getCLongField(this, 21);
	}
	/// best accumulative cost from bos node to this node.
	@CLong 
	@Field(21) 
	public mecab_node_t cost(long cost) {
		this.io.setCLongField(this, 21, cost);
		return this;
	}
	public mecab_node_t(Pointer pointer) {
		super(pointer);
	}
}
