language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2
sudo: required
before_install:
  - sudo add-apt-repository ppa:gezakovacs/japanese-nlp -y
  - sudo apt-get update -qq
  - sudo apt-get install -y juman mecab
